"""empty message

Revision ID: 2f28407dfbd2
Revises: d0ee23ec91ad
Create Date: 2023-08-17 06:10:18.451115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f28407dfbd2'
down_revision = 'd0ee23ec91ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_user_name_key', type_='unique')
        batch_op.drop_column('token')
        batch_op.drop_column('user_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('token', sa.VARCHAR(length=60), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('user_user_name_key', ['user_name'])

    # ### end Alembic commands ###
